export const INVITE_BENEFIT = 5000;
export const INVITE_TIER_AWARD = 50000;

export const GAME_DAILY_LIMIT = 3;
export const GAME_HEALTH = 3;
export const GAME_BENEFIT_VALUE = 10;
export const GAME_ENEMY_BENEFIT_VALUE = 100;

export const GAME_CONFIG = {
  BASE_SPEED_MULTIPLIER: 1,
  SPEED_UP_INTERVAL: 20000,
  SPEED_UP_MULTIPLIER: 0.1,
  SHIP_SPEED_UP_MULTIPLIER: 0.05,
  GODMODE_COOLDOWN: 5,
  SHIP_SPEED: 10,
  SHIP_ROTATION_SPEED: 0.03,
  SHIP_MAX_ROTATION: 0.1,
  BULLET_SPEED: 50,
  SHOOT_DELAY: 250, // ms
  BENEFIT_SPAWN_DELAY: 250, // ms
  ENEMY_SPAWN_DELAY: 750, // ms
  SHIP_SHAKE_SPEED: 1,
  STAR_SPEED: 25,
  BENEFIT: {
    POINT: 10,
    MIN_X_SPEED: 2,
    MAX_X_SPEED: 3.5,
    MIN_SPEED: 5,
    MAX_SPEED: 7,
    MIN_SIZE: 25,
    MAX_SIZE: 50,
  },
  ENEMY: {
    POINT: 100,
    MIN_X_SPEED: 2,
    MAX_X_SPEED: 4,
    MIN_SPEED: 5,
    MAX_SPEED: 6,
    MIN_SIZE: 50,
    MAX_SIZE: 100,
  },
};
